name: Release Builds

on:
  push:
    tags:
      - "v*" # Triggers only on version tags like v0.1.0

permissions:
  contents: write # Needed for GitHub release upload

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: linux-x86_64
            ext: tar.gz
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            artifact_name: linux-musl-x86_64
            ext: tar.gz
            target: x86_64-unknown-linux-musl
          - os: windows-latest
            artifact_name: windows-x86_64
            ext: zip
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            artifact_name: macos-x86_64
            ext: tar.gz
            target: x86_64-apple-darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Build release binary
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Package binary (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          mkdir -p artifacts
          VERSION=${GITHUB_REF#refs/tags/}
          BIN_NAME="stash"
          BIN_PATH=target/${{ matrix.target }}/release/${BIN_NAME}
          cp ${BIN_PATH} artifacts/
          cd artifacts
          tar -czf ../${BIN_NAME}-${VERSION}-${{ matrix.artifact_name }}.tar.gz ${BIN_NAME}

      - name: Package binary (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir artifacts
          $VERSION="${env:GITHUB_REF}" -replace 'refs/tags/', ''
          $BIN_NAME="stash.exe"
          $BIN_PATH="target\${{ matrix.target }}\release\${BIN_NAME}"
          Copy-Item $BIN_PATH artifacts\
          Compress-Archive -Path artifacts\$BIN_NAME -DestinationPath "${{ github.workspace }}\stash-$VERSION-${{ matrix.artifact_name }}.zip"

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            stash-*.zip
            stash-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
